/*
 * *
 *  * Copyright (C) 2016 Canh Ngo <canhnt@gmail.com>
 *  * All rights reserved.
 *  *
 *  * This library is free software; you can redistribute it and/or
 *  * modify it under the terms of the GNU Lesser General Public
 *  * License as published by the Free Software Foundation; either
 *  * version 3.0 of the License, or any later version.
 *  *
 *  * This library is distributed in the hope that it will be useful,
 *  * but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  * Lesser General Public License for more details.
 *  *
 *  * You should have received a copy of the GNU Lesser General Public
 *  * License along with this library; if not, write to the Free Software
 *  * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *  * MA 02110-1301 USA
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.01 at 04:14:23 PM CEST 
//


package nl.uva.sne.xacml.profiles._2_0_.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TargetType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="TargetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Subjects" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Resources" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Actions" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Environments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetType", propOrder = {
        "subjects",
        "resources",
        "actions",
        "environments"
})
public class TargetType {

    @XmlElement(name = "Actions")
    protected ActionsType actions;
    @XmlElement(name = "Environments")
    protected EnvironmentsType environments;
    @XmlElement(name = "Resources")
    protected ResourcesType resources;
    @XmlElement(name = "Subjects")
    protected SubjectsType subjects;

    /**
     * Gets the value of the actions property.
     *
     * @return possible object is {@link ActionsType }
     */
    public ActionsType getActions() {
        return actions;
    }

    /**
     * Gets the value of the environments property.
     *
     * @return possible object is {@link EnvironmentsType }
     */
    public EnvironmentsType getEnvironments() {
        return environments;
    }

    /**
     * Gets the value of the resources property.
     *
     * @return possible object is {@link ResourcesType }
     */
    public ResourcesType getResources() {
        return resources;
    }

    /**
     * Gets the value of the subjects property.
     *
     * @return possible object is {@link SubjectsType }
     */
    public SubjectsType getSubjects() {
        return subjects;
    }

    /**
     * Sets the value of the actions property.
     *
     * @param value allowed object is {@link ActionsType }
     */
    public void setActions(ActionsType value) {
        this.actions = value;
    }

    /**
     * Sets the value of the environments property.
     *
     * @param value allowed object is {@link EnvironmentsType }
     */
    public void setEnvironments(EnvironmentsType value) {
        this.environments = value;
    }

    /**
     * Sets the value of the resources property.
     *
     * @param value allowed object is {@link ResourcesType }
     */
    public void setResources(ResourcesType value) {
        this.resources = value;
    }

    /**
     * Sets the value of the subjects property.
     *
     * @param value allowed object is {@link SubjectsType }
     */
    public void setSubjects(SubjectsType value) {
        this.subjects = value;
    }

}
