//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 11:44:08 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:xacml:3.0:core:schema:wd-17", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package oasis.names.tc.xacml._3_0.core.schema.wd_17;
